### ISSUE TITLE
MOBILE Customization functionality (HIGH PRIORITY - For Today)

### ISSUE THREAD

**Issue by JasonSpinKil** [j0die/spk-bridal-wh#26]
On mobile there should be vertical lines separating the sections. Additionally, you can't change the image displayed with the buttons, only by swiping like on mobile.

![screen shot 2017-04-07 at 1 08 34 pm](https://cloud.githubusercontent.com/assets/25065650/24818133/1a2d0462-1b94-11e7-9a96-3acc588ea14e.png)

**Comment by contentisrelative** [comment]
Also - this is an issue for _Desktop_ on Safari 10.0.3, as well !
