### ISSUE TITLE
Slider Progress Dots - Adjustments/Fixes

### ISSUE THREAD

**Issue by contentisrelative** [j0die/spk-bridal-wh#34]
**Desktop - Reduce Progress Dot Stroke**
- Can we reduce the stroke width by almost half, so it is more delicate

_example:_
<img width="178" alt="screen shot 2017-04-10 at 3 25 38 pm" src="https://cloud.githubusercontent.com/assets/24306129/24885193/fc850048-1e01-11e7-9966-254510d3b9fe.png">

**Desktop, Mobile, etc - Remove White Edge**
- Bottom Edge of dots is slightly cut off, sometimes. Can we make sure that there is no white overlap on the dots? Examples Below show the problem:
<img width="268" alt="screen shot 2017-04-10 at 3 16 23 pm" src="https://cloud.githubusercontent.com/assets/24306129/24885283/7b234d6a-1e02-11e7-99d9-64da3e7e5265.png">
<img width="154" alt="screen shot 2017-04-10 at 3 30 04 pm" src="https://cloud.githubusercontent.com/assets/24306129/24885318/a117bd44-1e02-11e7-8a07-7990229754d7.png">
<img width="161" alt="screen shot 2017-04-10 at 3 30 12 pm" src="https://cloud.githubusercontent.com/assets/24306129/24885319/a13b1c3a-1e02-11e7-9edd-d0ec9abc9e0d.png">

**Comment by sqbiz** [comment]
fixed
